
name: Build

on:
  push:
    branches: [ main ]
jobs:
  build:


    steps:
      - name: Checkout source code.
        uses: actions/checkout@v4
      - name: echo Hello
        run: echo "Hello"



